redis:
  image: redis
  container_name: redis
  expose:
    - 6379

video-service:
  build: ./
  volumes:
    - ./:/usr/src/app
  ports:
    - 8899:8899
  environment:
    - NODE_ENV=development
    - PORT=8899
  links:
    - redis
  command:
    sh -c 'npm i && npm rebuild && npm run setup-env'